apiVersion: v1
kind: Pod
metadata:
  name: example-curl
  labels:
    name: example-curl
spec:
  containers:
  - name: example-curl
    image: alpine:latest  # Use the appropriate version
    command: ["sleep"]
    args: ["3600"] 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
